/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMessages: typeof import('./components/AppMessages.vue')['default']
    AppTextInput: typeof import('./components/AppTextInput.vue')['default']
    AppUserInput: typeof import('./components/AppUserInput.vue')['default']
    Assistants: typeof import('./components/Assistants.vue')['default']
    Auth: typeof import('./components/Auth.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    ChatBot: typeof import('./components/ChatBot.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    EventSource: (typeof import("./components/EventSource.vue"))["default"]
    FileObjects: typeof import('./components/FileObjects.vue')['default']
    FilesInput: typeof import('./components/FilesInput.vue')['default']
    GradientButton: typeof import('./components/GradientButton.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    Microphone: typeof import('./components/Microphone.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    New: (typeof import("./components/New.vue"))["default"]
    Notifier: typeof import('./components/Notifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: (typeof import("./components/Test.vue"))["default"]
    TextBlock: typeof import('./components/TextBlock.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
    ThreadMessages: typeof import('./components/ThreadMessages.vue')['default']
    Threads: typeof import('./components/Threads.vue')['default']
    UserFunctions: (typeof import("./components/UserFunctions.vue"))["default"]
    UserInput: typeof import('./components/UserInput.vue')['default']
    VButton: typeof import('./components/VButton.vue')['default']
  }
}
