

services:
  db:
    container_name: quipubase
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5454:5454"
    env_file:
      - ./db/.env
    volumes:
      - ./db:/app
    networks:
      - quipu

  transcribe:
    container_name: transcribe
    build:
      context: ./transcribe
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    volumes:
      - ./transcribe:/app
    networks:
      - quipu
    env_file:
      - ./transcribe/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]

  voice:
    container_name: voice
    build:
      context: ./voice
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./voice:/app
    networks:
      - quipu
    env_file:
      - ./voice/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]

  embeddings:
    container_name: embeddings
    build:
      context: ./embeddings
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./embeddings:/app
    networks:
      - quipu

  chat:
    container_name: chat
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./chat:/app
    networks:
      - quipu
    env_file:
      - ./chat/.env

  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    networks:
      - quipu


networks:
  quipu:
    driver: bridge