services:
  db:
    container_name: quipubase
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "5454:5454"
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - quipu

networks:
  quipu:
    driver: bridge