services:

  quipubase:
    container_name: quipubase
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5454:5454"
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - quipu


networks:
  quipu:
    driver: bridge