[tool.poetry]
name = "quipubase"
version = "0.0.1-alpha"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
cython = "^3.0.10"
orjson = "^3.10.3"
numpy = "^1.26.4"
hnswlib = "^0.8.0"
python-dotenv = "^1.0.1"
uvicorn = "^0.29.0"
fastapi-slim = "^0.111.0"
python-multipart = "^0.0.9"
openai = "^1.30.2"



[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
black = "^21.12b0"
isort = "^5.10.2"
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"

[tool.poetry.scripts]
quipubase = "quipubase.cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
