[tool.poetry]
name = "quipubase"
<<<<<<< HEAD
version = "0.0.2-alpha"
description = "A serverless document and vector database built at the edge for AI applications."
authors = ["Oscar Bahamonde <o.bahamonde@globant.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
=======
version = "0.1.0"
description = ""
authors = ["o-bahamonde_globant <o.bahamonde@globant.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
>>>>>>> 8bb18d5d07cbbe1c18c42817158c463fd018a180
cython = "^3.0.10"
orjson = "^3.10.3"
numpy = "^1.26.4"
hnswlib = "^0.8.0"
python-dotenv = "^1.0.1"
uvicorn = "^0.29.0"
fastapi-slim = "^0.111.0"
<<<<<<< HEAD
openai = "^1.30.3"



=======
python-multipart = "^0.0.9"
openai = "^1.30.3"
>>>>>>> 8bb18d5d07cbbe1c18c42817158c463fd018a180

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
black = "^21.12b0"
isort = "^5.10.2"
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"

[tool.poetry.scripts]
quipubase = "quipubase.cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "Cython"]
build-backend = "poetry.core.masonry.api"
